# Generated by Django 2.0.3 on 2018-05-02 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import online_testing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.FileField(upload_to='answers/')),
                ('score', models.SmallIntegerField(default=-1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 6, 56, 56, 1360, tzinfo=utc))),
                ('submit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('papar_name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 6, 56, 56, 1360, tzinfo=utc))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 6, 56, 56, 1360, tzinfo=utc))),
                ('duration', models.IntegerField()),
                ('question_id_list', online_testing.models.ListField()),
                ('score_list', online_testing.models.ListField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('choice_list', online_testing.models.ListField()),
                ('answer_list', online_testing.models.ListField()),
                ('tag', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Choice', 'Choice'), ('Judge', 'Judge')], default='Choice', max_length=12)),
                ('level', models.IntegerField(choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Difficult'), (4, 'Very Difficult')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='examination',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_testing.Paper'),
        ),
    ]
