# Generated by Django 2.0.3 on 2018-05-05 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import online_testing.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('answers', models.FileField(null=True, upload_to='answers/')),
                ('score', models.SmallIntegerField(default=-1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 5, 5, 0, 53, 33, 480241, tzinfo=utc))),
                ('submit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 5, 5, 0, 53, 33, 476227, tzinfo=utc))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 5, 5, 0, 53, 33, 476227, tzinfo=utc))),
                ('duration', models.IntegerField()),
                ('score_list', online_testing.models.ListField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('choice_list', online_testing.models.ListField()),
                ('answer_list', online_testing.models.ListField()),
                ('tag', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Choice', 'Choice'), ('Judge', 'Judge')], default='Choice', max_length=12)),
                ('level', models.IntegerField(choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Difficult'), (4, 'Very Difficult')], default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Course')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='question_id_list',
            field=models.ManyToManyField(to='online_testing.Question'),
        ),
        migrations.AddField(
            model_name='examination',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_testing.Paper'),
        ),
        migrations.AddField(
            model_name='examination',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Student'),
        ),
        migrations.AddField(
            model_name='examination',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty'),
        ),
    ]
