# Generated by Django 2.0.3 on 2018-05-05 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 1, 10, 19, 471775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 1, 10, 19, 471775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 1, 10, 19, 471775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty'),
        ),
    ]
