# Generated by Django 2.0.3 on 2018-05-02 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_testing', '0004_auto_20180502_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 7, 59, 15, 852049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 7, 59, 15, 842047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 7, 59, 15, 842047, tzinfo=utc)),
        ),
    ]
