# Generated by Django 2.0.3 on 2018-05-05 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_testing', '0005_auto_20180505_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='answers',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 11, 32, 15, 978919)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 11, 32, 15, 978919)),
        ),
    ]
